### ISSUE TITLE
Create and submit a sitemap to help search engines crawl and index the website.

### ISSUE THREAD

**Issue by jnarlyv** [nathandh/mywebclass-simulation#18] opened 2023-03-15 01:32 UTC
User Story: As product owner, I expect the web application to be easily searched by Google and other Search Engines to improve exposure and finding by educators.

Description: Effective sitemap are associated with improved search engine ranking

**Comment by nathandh** [comment] 2023-03-17 01:15
Duplicate of Backlog # 16 item to create Robots.txt file for search engine crawling. 
Resolving in favor of: https://github.com/nathandh/mywebclass-simulation/issues/16

**Closed by nathandh** 2023-03-17 01:15 UTC
Labels: Sprint 1 (03-11-2023 to 03-24-2023), Backend
