### ISSUE TITLE
Identify errors and warnings in response to W3C validator tool.

### ISSUE THREAD

**Issue by jnarlyv** [nathandh/mywebclass-simulation#14] opened 2023-03-15 01:12 UTC
User Story: As a web developer, I want to ensure that my website adheres to web standards and is accessible to all users, so that I can provide a high-quality user experience and avoid potential issues with usability and search engine optimization.

Description: Web development team identify and address warnings related to W3C validator to ensure that website  is in compliance with standards

**Comment by nathandh** [comment] 2023-03-17 01:20
Duplicate of # 13. Resolving in favor of # 13: https://github.com/nathandh/mywebclass-simulation/issues/13

**Closed by nathandh** 2023-03-17 01:20 UTC
Labels: Sprint 1 (03-11-2023 to 03-24-2023)
